import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

import { SCHEMA_EMISSION_GUIDE } from './instructions.js';

export const START_SENTINEL = '<!-- motionworks-instructions-start -->';
export const END_SENTINEL = '<!-- motionworks-instructions-end -->';
const VERSION_LINE_PREFIX = '<!-- motionworks-version: ';
const VERSION_LINE_SUFFIX = ' -->';

export interface StanzaScan {
  present: boolean;
  version: string | null;
  /** Byte-index at which the start sentinel begins, or null if not present. */
  startIndex: number | null;
  /** Byte-index just after the end sentinel, or null if not present. */
  endIndex: number | null;
}

/** Scans a CLAUDE.md string for the MotionWorks stanza. */
export function scanClaudeMd(contents: string): StanzaScan {
  const startIdx = contents.indexOf(START_SENTINEL);
  if (startIdx === -1) {
    return { present: false, version: null, startIndex: null, endIndex: null };
  }
  const endIdxRaw = contents.indexOf(END_SENTINEL, startIdx + START_SENTINEL.length);
  if (endIdxRaw === -1) {
    return { present: false, version: null, startIndex: null, endIndex: null };
  }
  const inner = contents.slice(startIdx + START_SENTINEL.length, endIdxRaw);
  let version: string | null = null;
  for (const rawLine of inner.split('\n')) {
    const line = rawLine.trim();
    if (line.startsWith(VERSION_LINE_PREFIX) && line.endsWith(VERSION_LINE_SUFFIX)) {
      version = line.slice(VERSION_LINE_PREFIX.length, line.length - VERSION_LINE_SUFFIX.length).trim();
      break;
    }
  }
  return {
    present: true,
    version,
    startIndex: startIdx,
    endIndex: endIdxRaw + END_SENTINEL.length,
  };
}

/**
 * The standalone file the full schema emission guide is written to. The
 * instruction files (CLAUDE.md / AGENTS.md) only carry a short pointer to it
 * (see `renderStanza`) so they stay small and their upgrade diffs stay legible.
 */
export const GUIDE_FILE = 'MOTIONWORKS.md';

/**
 * Produces the sentinel-delimited *reference* stanza written into CLAUDE.md /
 * AGENTS.md. It is intentionally tiny — a version marker plus a pointer to
 * {@link GUIDE_FILE}, which holds the full guide. Keeping the guide out of the
 * instruction file avoids bloating it and keeps `init` upgrade diffs to a
 * couple of lines.
 */
export function renderStanza(version: string): string {
  return [
    START_SENTINEL,
    `${VERSION_LINE_PREFIX}${version}${VERSION_LINE_SUFFIX}`,
    '',
    `This project uses **MotionWorks** for motion design. Before you implement or refine any motion effect, read [\`${GUIDE_FILE}\`](./${GUIDE_FILE}) — it defines how to mount the overlay and how to emit the effect registrations MotionWorks requires. The same guide is available anytime from the \`motionworks_get_instructions\` MCP tool.`,
    END_SENTINEL,
  ].join('\n');
}

/**
 * Produces the full contents of {@link GUIDE_FILE}: a version marker, a
 * "generated" header, and the schema emission guide. This file is owned by
 * `motionworks init` and regenerated wholesale on upgrade.
 */
export function renderGuideDoc(version: string): string {
  return [
    `${VERSION_LINE_PREFIX}${version}${VERSION_LINE_SUFFIX}`,
    '<!-- Generated by `motionworks init`. Do not edit by hand; re-run `motionworks init` to update. -->',
    '',
    SCHEMA_EMISSION_GUIDE,
    '',
  ].join('\n');
}

// The agent instruction files the stanza can live in. CLAUDE.md is read by
// Claude Code; AGENTS.md by Codex CLI and other AGENTS.md-convention agents.
export const INSTRUCTION_FILES = ['CLAUDE.md', 'AGENTS.md'] as const;
export type InstructionFile = (typeof INSTRUCTION_FILES)[number];

export function instructionFilePath(cwd: string, file: InstructionFile): string {
  return join(cwd, file);
}

/** Reads an instruction file if present; returns null when it does not exist. */
export async function readInstructionFile(
  cwd: string,
  file: InstructionFile,
): Promise<string | null> {
  try {
    return await readFile(instructionFilePath(cwd, file), 'utf8');
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === 'ENOENT') return null;
    throw err;
  }
}

export async function writeInstructionFile(
  cwd: string,
  file: InstructionFile,
  contents: string,
): Promise<void> {
  await writeFile(instructionFilePath(cwd, file), contents, 'utf8');
}

export function guideFilePath(cwd: string): string {
  return join(cwd, GUIDE_FILE);
}

/** Reads the guide file ({@link GUIDE_FILE}) if present; null when missing. */
export async function readGuideFile(cwd: string): Promise<string | null> {
  try {
    return await readFile(guideFilePath(cwd), 'utf8');
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === 'ENOENT') return null;
    throw err;
  }
}

export async function writeGuideFile(cwd: string, contents: string): Promise<void> {
  await writeFile(guideFilePath(cwd), contents, 'utf8');
}

export function claudeMdPath(cwd: string): string {
  return instructionFilePath(cwd, 'CLAUDE.md');
}

/** Reads CLAUDE.md if present; returns null when the file does not exist. */
export async function readClaudeMd(cwd: string): Promise<string | null> {
  return readInstructionFile(cwd, 'CLAUDE.md');
}

export async function writeClaudeMd(cwd: string, contents: string): Promise<void> {
  await writeInstructionFile(cwd, 'CLAUDE.md', contents);
}

/**
 * Compares two semver-ish version strings (e.g. "1.2.0", "0.1.0-beta.1").
 * Returns -1 if a<b, 0 if a==b, 1 if a>b. Non-numeric segments compare lexically.
 */
export function compareVersions(a: string, b: string): number {
  const parse = (v: string): (number | string)[] => {
    const [core, pre = ''] = v.split('-', 2) as [string, string?];
    const nums = core.split('.').map((n) => {
      const asNum = Number(n);
      return Number.isFinite(asNum) ? asNum : n;
    });
    const preParts = pre === '' ? [] : pre.split('.').map((n) => {
      const asNum = Number(n);
      return Number.isFinite(asNum) ? asNum : n;
    });
    return [...nums, ...(pre === '' ? [] : ['-', ...preParts])];
  };
  const A = parse(a);
  const B = parse(b);
  const len = Math.max(A.length, B.length);
  for (let i = 0; i < len; i++) {
    const av = A[i];
    const bv = B[i];
    if (av === undefined && bv === undefined) return 0;
    // Absent > present when the shorter one has no prerelease boundary.
    if (av === undefined) return 1;
    if (bv === undefined) return -1;
    if (av === bv) continue;
    if (typeof av === 'number' && typeof bv === 'number') return av < bv ? -1 : 1;
    return String(av) < String(bv) ? -1 : 1;
  }
  return 0;
}
